version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgres://shopper:password@db:5432/shopper'

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: shopper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopper

volumes:
  pgdata:
