version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    # volumes:
    #   - .:/app
    # - /app/node_modules # Evita sobrescrever node_modules
    depends_on:
      - db
      - migrations
    environment:
      DATABASE_URL: 'postgres://shopper:password@db:5432/shopper'

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: shopper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopper

  migrations:
    image: postgres:14
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: >
      sh -c "until pg_isready -h db -U shopper; do echo 'Waiting for db...'; sleep 2; done;
             PGPASSWORD=password psql -h db -U shopper -d shopper -f /app/schemas/measures_table.sql"

volumes:
  pgdata:
